apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-next-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bun-next-app
  template:
    metadata:
      labels:
        app: bun-next-app
    spec:
      containers:
        - name: bun-next-app
          image: niharlnx/bun-next-app:4c790e06432fef97a804c27c0d573c22505c6e4b
          ports:
            - containerPort: 3000
